package:
  name: pipelign
  version: "v0.1"

#source:
#  git_rev: "v0.1"
#  git_url: https://github.com/sdwfrost/pipelign.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - biopython
    - ete3
    - joblib
    - mafft
    - iqtree
    - hmmer
    - cd-hit

about:
  home: https://github.com/asmmhossain/pipelign
  license: MIT
  license_file: LICENSE
