package:
  name: pipelign
  version: "v0.1"

source:
  git_rev: "v0.1"
  git_url: https://github.com/sdwfrost/pipelign.git

channels:
  - bioconda

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - biopython
    - ete3
    - mafft
    - cd-hit
    - iqtree
    - hmmer

about:
  home: https://github.com/asmmhossain/pipelign
  license: MIT
  license_file: LICENSE
